-- Schema for Scopus Journals table in Supabase
CREATE TABLE IF NOT EXISTS public.scopus_journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journal_name TEXT NOT NULL,
    publisher TEXT,
    issn TEXT,
    e_issn TEXT,
    subject_area TEXT,
    citescore NUMERIC,
    sjr NUMERIC,
    snip NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_journal_issn UNIQUE (journal_name, issn, e_issn)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_scopus_journal_name ON public.scopus_journals(journal_name);
CREATE INDEX IF NOT EXISTS idx_scopus_citescore ON public.scopus_journals(citescore DESC);
CREATE INDEX IF NOT EXISTS idx_scopus_issn ON public.scopus_journals(issn);
CREATE INDEX IF NOT EXISTS idx_scopus_e_issn ON public.scopus_journals(e_issn);

-- Enable Row Level Security (RLS)
ALTER TABLE public.scopus_journals ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access" ON public.scopus_journals
    FOR SELECT USING (true);

-- Allow service_role or authenticated users with key to insert/update
CREATE POLICY "Allow service_role insert and update" ON public.scopus_journals
    FOR ALL USING (true) WITH CHECK (true);
